---
title: "07_sensitivity_beniot code"
output: html_document
date: "2024-11-03"
---

#code from David Beniot

```{r}
library(multisensi)
library(sensitivity)
library(mizer)

 rm(list =ls()) # clear memory
```


```{r}
#Load mizer details
species_params2 <- readRDS("tuned_params_v4.rds")

species_params2<- as.data.frame(species_params2@species_params)

# View the resulting data frame
head(species_params2)

#i've left this in but need to double check it's appropriate
kappa <- 10
species_params2$R_max <- kappa * species_params2$w_inf^(-1.5)
species_params2$R_max <- species_params2$R_max * 100



```


```{r}
#interaction matrix
inter <- read.csv("sp_1_interactions.csv", header = TRUE, sep = ",", row.names = NULL, stringsAsFactors = TRUE )
# inter <- inter[-c(1)]
# colnames(inter) <- c("Common Shiner", "Cisco", "Freshwater Drum", "Northern Pike", "Trout-perch", "Walleye", "Yellow Perch")
# rownames(inter) <- colnames(inter)
inter <- as.matrix(inter)
```


#setting +/- 10% change with important parameters------

```{r}
m <- 10000

#from Benoit's study - these are the 10 most important parameters according to the morris test. They are species specific. i.e. k_vb.1 = commmon shiner von bert growth coefficient. Since we didn't run the morris test - lets just test all species k_vb value.

# Xb <- data.frame(k_vb.6=runif(m,min=0.1818, max = 0.2222), w_inf.4 = runif(m,min=10023.99, max = 12251.55), k_vb.1 = runif(m, min = 0.5184, max = 0.6336),
#                  k_vb.5 = runif(m, min = 0.39474, max = 0.48246), w_inf.1 = runif(m, min = 36.9, max = 45.1), R_max.5 = runif(m, min = 3.428205, max = 4.190028),
#                  w_inf.6 = runif(m, min = 1927.233, max = 2355.507), w_inf.2 = runif(m, min = 636.5232, max = 777.9728), k_vb.4 = runif(m, min = 0.0918, max = 0.1122),
#                  w_inf.5 = runif(m, min = 36.9, max = 45.1))




```




