---
title: "07_sensitivity_biomass"
output: html_document
date: "2024-11-03"
---


#code from David Beniot

```{r}
library(multisensi)
library(sensitivity)
library(mizer)

 rm(list =ls()) # clear memory
```


```{r}
#Load mizer details
species_params2 <- readRDS("tuned_params_v4.rds")

species_params2<- as.data.frame(species_params2@species_params)

# View the resulting data frame
head(species_params2)

#i've left this in but need to double check it's appropriate
kappa <- 10
species_params2$R_max <- kappa * species_params2$w_inf^(-1.5)
species_params2$R_max <- species_params2$R_max * 100



```


```{r}
#interaction matrix
inter <- read.csv("sp_1_interactions.csv", header = TRUE, sep = ",", row.names = NULL, stringsAsFactors = TRUE )
# inter <- inter[-c(1)]
# colnames(inter) <- c("Common Shiner", "Cisco", "Freshwater Drum", "Northern Pike", "Trout-perch", "Walleye", "Yellow Perch")
# rownames(inter) <- colnames(inter)

# Create the interaction matrix (example, modify if needed)
inter <- matrix(c(
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
  1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
), nrow = 13, byrow = TRUE,
dimnames = list(
  c("Euphausia similis", "Thysannoessa macura", "Sergestes spp", "Themisto spp", 
    "Lampanyctus australis", "Nannobrachium achirus", "Cyclothone spp", 
    "Bathylagus spp", "Cranchidae", "Chaetognath", "Gymnosomata", 
    "Pyrosoma atlanticum", "Atolla wyvillei"),
  c("Euphausia similis", "Thysannoessa macura", "Sergestes spp", "Themisto spp", 
    "Lampanyctus australis", "Nannobrachium achirus", "Cyclothone spp", 
    "Bathylagus spp", "Cranchidae", "Chaetognath", "Gymnosomata", 
    "Pyrosoma atlanticum", "Atolla wyvillei")
))

# Convert the matrix to numeric
inter <- apply(inter, 2, as.numeric)

# Confirm that the matrix is numeric
str(inter)



```


#setting +/- 10% change with important parameters------

```{r}

#from Benoit's study - these are the 10 most important parameters according to the morris test. They are species specific. i.e. k_vb.1 = commmon shiner von bert growth coefficient. Since we didn't run the morris test - lets just test all species k_vb value.

# Xb <- data.frame(k_vb.6=runif(m,min=0.1818, max = 0.2222), w_inf.4 = runif(m,min=10023.99, max = 12251.55), k_vb.1 = runif(m, min = 0.5184, max = 0.6336),
#                  k_vb.5 = runif(m, min = 0.39474, max = 0.48246), w_inf.1 = runif(m, min = 36.9, max = 45.1), R_max.5 = runif(m, min = 3.428205, max = 4.190028),
#                  w_inf.6 = runif(m, min = 1927.233, max = 2355.507), w_inf.2 = runif(m, min = 636.5232, max = 777.9728), k_vb.4 = runif(m, min = 0.0918, max = 0.1122),
#                  w_inf.5 = runif(m, min = 36.9, max = 45.1))



# Number of samples for each parameter (choose an appropriate number, e.g., m = 1000)
m <- 1000 

# Create a data frame with random values for `k_vb` altered by ±10% for each species
Xb <- data.frame(
  k_vb.1 = runif(m, min = 0.9 * species_params2$k_vb[1], max = 1.1 * species_params2$k_vb[1]),
  k_vb.2 = runif(m, min = 0.9 * species_params2$k_vb[2], max = 1.1 * species_params2$k_vb[2]),
  k_vb.3 = runif(m, min = 0.9 * species_params2$k_vb[3], max = 1.1 * species_params2$k_vb[3]),
  k_vb.4 = runif(m, min = 0.9 * species_params2$k_vb[4], max = 1.1 * species_params2$k_vb[4]),
  k_vb.5 = runif(m, min = 0.9 * species_params2$k_vb[5], max = 1.1 * species_params2$k_vb[5]),
  k_vb.6 = runif(m, min = 0.9 * species_params2$k_vb[6], max = 1.1 * species_params2$k_vb[6]),
  k_vb.7 = runif(m, min = 0.9 * species_params2$k_vb[7], max = 1.1 * species_params2$k_vb[7]),
  k_vb.8 = runif(m, min = 0.9 * species_params2$k_vb[8], max = 1.1 * species_params2$k_vb[8]),
  k_vb.9 = runif(m, min = 0.9 * species_params2$k_vb[9], max = 1.1 * species_params2$k_vb[9]),
  k_vb.10 = runif(m, min = 0.9 * species_params2$k_vb[10], max = 1.1 * species_params2$k_vb[10]),
  k_vb.11 = runif(m, min = 0.9 * species_params2$k_vb[11], max = 1.1 * species_params2$k_vb[11]),
  k_vb.12 = runif(m, min = 0.9 * species_params2$k_vb[12], max = 1.1 * species_params2$k_vb[12]),
  k_vb.13 = runif(m, min = 0.9 * species_params2$k_vb[13], max = 1.1 * species_params2$k_vb[13])
)

# View the generated data frame
head(Xb)



```

```{r}
runsobol <- function(k_vb.1, k_vb.2, k_vb.3, k_vb.4, k_vb.5, k_vb.6, k_vb.7, k_vb.8, k_vb.9, k_vb.10, k_vb.11, k_vb.12, k_vb.13) {
  # Assign the new `k_vb` values to each species in `species_params2`
  species_params2$k_vb[1] <- k_vb.1
  species_params2$k_vb[2] <- k_vb.2
  species_params2$k_vb[3] <- k_vb.3
  species_params2$k_vb[4] <- k_vb.4
  species_params2$k_vb[5] <- k_vb.5
  species_params2$k_vb[6] <- k_vb.6
  species_params2$k_vb[7] <- k_vb.7
  species_params2$k_vb[8] <- k_vb.8
  species_params2$k_vb[9] <- k_vb.9
  species_params2$k_vb[10] <- k_vb.10
  species_params2$k_vb[11] <- k_vb.11
  species_params2$k_vb[12] <- k_vb.12
  species_params2$k_vb[13] <- k_vb.13
  
  # Create MizerParams object with the updated `species_params2`
  params <- newMultispeciesParams(species_params = species_params2, interaction = inter, kappa = 10, w_pp_cutoff = 2)
  
  # Run the simulation
  sim <- project(params, effort = 0, t_max = 100, dt = 0.1, t_save = 1)
  
  # Extract and return the community slope at the final timestep
  output <- getBiomass(sim)[100, , ]$slope
  return(output)
}

```


```{r}
runsobol2 <- function(X) {
  out <- matrix(nrow = nrow(X), ncol = 1, NA)
  for (i in 1:nrow(X)) {
    out[i, ] <- runsobol(X$k_vb.1[i], X$k_vb.2[i], X$k_vb.3[i], X$k_vb.4[i], X$k_vb.5[i],
                         X$k_vb.6[i], X$k_vb.7[i], X$k_vb.8[i], X$k_vb.9[i], X$k_vb.10[i],
                         X$k_vb.11[i], X$k_vb.12[i], X$k_vb.13[i])
  }
  out <- as.data.frame(out)
  return(out)
}

```


```{r}
seq.sobol <- multisensi(design = sobol2007, model = runsobol2,
                        reduction = NULL, analysis = analysis.sensitivity, center = TRUE,
                        design.args = list(X1 = Xb[1:(m/2), ], X2 = Xb[(1 + m/2):m, ], nboot = 100),
                        analysis.args = list(keep.outputs = FALSE))


```

