---
title: "01_SOLACE_biomass"
output: html_document
date: "2024-05-08"
---

# Load data -------------------------------------------------------------

```{r}
library(ggplot2)
library(ggrepel)
library(tidyverse)
library(readr)
library(dplyr)
library(ggh4x)
library(rcartocolor)
library(gridExtra)
library(viridis)
library(here) # uses the here::here() function to get the working directory of Rproj folder
library(geosphere)



rm(list =ls()) # clear memory
catchcomp_total <- read.csv("C:/Users/kbaker5/OneDrive - University of Tasmania/Desktop/PhD_Salamanca/RstudioProjects/02_MesoMizer/input/Input_01_IN2020_V08_CatchComp_allsites_nolength.csv")


```


#calculate model domain area

```{r}

# Define the polygon coordinates
SOTS_region <- data.frame(x=c(144.79, 139.43, 139.43, 144.79), y=c(-45.51, -45.51, -50.03, -50.03))

# Calculate the area of the polygon in square meters
polygon_m3 <- areaPolygon(cbind(SOTS_region$x, SOTS_region$y)) *1000

# Print the area of the polygon in m-2
print(polygon_m3)


```



#data wrangle


```{r}
catchcomp_total1 <- catchcomp_total %>% 
  dplyr::select(Site, daylight, Depth_Stratum, Deployment, Taxa_updated,Taxa_PLAOS,Abd_Std_nosm3_sp, nos, weight_g, av_weight,
                Weight_Std_gm3_sp)  %>% 
  mutate(Depth_Stratum = case_when(Depth_Stratum == "Lmeso" ~ "LM",
                                          Depth_Stratum == "Meso" ~ "UM",
                                          Depth_Stratum == "Epi" ~ "E"))


catchcomp_total1 <- na.omit(catchcomp_total1)
catchcomp_total1$Depth_Stratum <- factor(as.factor(catchcomp_total1$Depth_Stratum),levels = c("LM", "UM", "E"))
catchcomp_total1$Site <- factor(as.factor(catchcomp_total1$Site), levels = c("SOTS","55S","58S"))


```


```{r}
# Define the list of taxa of interest
taxa_of_interest <- c("Euphausia similis", "Thysannoessa macura", "Sergestes spp", "Themisto spp", 
                      "Lampanyctus australis", "Nannobrachium achirus", "Cyclothone spp", 
                      "Bathylagus spp", "Cranchidae", "Chaetognath", "Gymnosomata", 
                      "Pyrosoma atlanticum", "Atolla wyvillei")

# Filter the dataframe for the site "SOTS"
filtered_data <- catchcomp_total1 %>%
  filter(Site == "SOTS")%>%
  filter(!(Taxa_PLAOS %in% c("Medusa", "Siphonophore", "Other", "Salp other", "Ctenophore" )))

# Calculate the total biomass for the taxa of interest
total_biomass_taxa_interest <- filtered_data %>%
  filter(Taxa_updated %in% taxa_of_interest) %>%
  summarise(total_biomass = sum(Weight_Std_gm3_sp, na.rm = TRUE)) %>%
  pull(total_biomass)

# Calculate the total biomass for all taxa
total_biomass_all <- filtered_data %>%
  summarise(total_biomass = sum(Weight_Std_gm3_sp, na.rm = TRUE)) %>%
  pull(total_biomass)

# Calculate the percentage of total biomass for the taxa of interest
percentage_biomass <- (total_biomass_taxa_interest / total_biomass_all) * 100

# Print the result
print(percentage_biomass)

```



#find taxa that make up 80% of biomass at SOTS

```{r}

# Filter the dataframe for the site "SOTS" and exclude specific taxa
filtered_data <- catchcomp_total1 %>%
  filter(Site == "SOTS") %>%
  filter(!(Taxa_PLAOS %in% c("Medusa", "Siphonophore", "Other", "Salp other", "Ctenophore" )))


# Calculate total weight per species, arrange by weight, and calculate cumulative percentage
top_species <- filtered_data %>%
  group_by(Site, daylight, Depth_Stratum, Deployment, Taxa_updated) %>%
  summarise(StdWt = sum(Weight_Std_gm3_sp)) %>% 
  ungroup() %>% 
  group_by(Taxa_updated) %>% 
  summarise(av_weight = mean(StdWt)) %>% 
  arrange(desc(av_weight)) %>%
  mutate(cumulative_percentage = cumsum(av_weight) / sum(av_weight) * 100)

# Filter species that comprise 80% of the total weight
species_95_percent <- top_species %>%
  filter(cumulative_percentage <= 95)

# View the result
print(species_95_percent)

```

```{r}
c("Euphausia similis","Thysannoessa macura","Sergestes spp", "Themisto spp", "Lampanyctus australis","Nannobrachium achirus","Cyclothone spp","Bathylagus spp","Cranchidae","Chaetognath","Gymnosomata","Pyrosoma atlanticum","Atolla wyvillei")
```



#filter for target species

```{r}
catchcomp_total1 <- catchcomp_total1 %>% 
 mutate(Taxa_updated = case_when(
    Taxa_updated == "Cranchiidae - undifferentiated" ~ "Cranchidae",
    Taxa_updated == "Euphausia similis similis" ~ "Euphausia similis",
    Taxa_updated == "Euphausia spp." ~ "Euphausia similis",
    Taxa_updated == "Euphausiidae - undifferentiated" ~ "Euphausia similis",
    Taxa_updated == "Order Gymnosomata - undifferentiated" ~ "Gymnosomata",
    Taxa_updated == "Order Euphausiacea - undifferentiated" ~ "Euphausia similis",
    Taxa_updated == "Phylum Chaetognatha - undifferentiated" ~ "Chaetognath",
    Taxa_updated == "Themisto gaudichaudii" ~ "Themisto spp",
    Taxa_updated == "Thysanoessa spp." ~ "Thysannoessa macura",
    TRUE ~ Taxa_updated
  ))


```

```{r}
Mesomizer_species <- catchcomp_total1 %>% 
  filter(Taxa_updated %in% c("Euphausia similis", "Thysannoessa macura", "Euphausia tricantha", "Gennadas spp.","Sergestes spp.", "Themisto spp", "Electrona antarctica", "Lampanyctus australis", "Nannobrachium achirus", "Cyclothone spp.", "Bathylagus spp.", "Cranchidae", "Chaetognath", "Gymnosomata", "Pyrosoma atlanticum", "Salpa thompsoni", "Atolla wyvillei", "Periphylla Periphylla", "Omnivorous copepod", "Carnivorous copepod"))%>% 
filter(Site == "SOTS") %>% 
  select(Site, daylight, Depth_Stratum, Deployment, Taxa_updated, Weight_Std_gm3_sp, nos, weight_g, av_weight, Abd_Std_nosm3_sp)

write.csv(Mesomizer_species, "SOLACE_biomass_filtered.csv")
```




#find biomass per species, depth at SOTS

```{r}


# Find biomass per species, depth & site
Biomass_deployment <- Mesomizer_species %>%
  group_by(Site, daylight, Depth_Stratum, Deployment, Taxa_updated) %>%
  summarise(StdWt = sum(Weight_Std_gm3_sp)) %>% #one weight per species per deployment
  ungroup() %>%
  group_by(daylight, Taxa_updated, Depth_Stratum) %>%  
  summarise(weight_mean_depth = mean(StdWt)) %>% #one weight per species per day/night & depth (average deployments)
   ungroup() %>% 
 mutate(g_m2 = case_when(
    Depth_Stratum == "E" ~ weight_mean_depth * 200,
    Depth_Stratum == "UM" ~ weight_mean_depth * 200,
    Depth_Stratum == "LM" ~ weight_mean_depth * 600
  )) %>% #convert from g m-3 to g m-2 by multipling by depth sampled. E = 200, UM = 200, LM = 600
  group_by(daylight, Taxa_updated) %>%
  summarise(
    Weight_wc_gm2_sp = sum(g_m2, na.rm = TRUE) #one weight per species per whole water column (add each layer)
  ) %>% 
  ungroup() %>% 
  group_by(Taxa_updated) %>% 
  summarise(
    weight_total_gm2_sp = mean(Weight_wc_gm2_sp) #average day and night values
  )

write.csv(Biomass_deployment, "Biomass_av_wc.csv")


Percentage_depth <- Mesomizer_species %>% 
  #select(Site, daylight, Depth_Stratum, Deployment, Taxa_updated, Weight_Std_gm3_sp) %>%
  group_by(Site, daylight, Depth_Stratum, Deployment, Taxa_updated) %>%
  summarise(StdWt = sum(Weight_Std_gm3_sp)) %>% #one weight per species per deployment
  ungroup() %>%
  group_by(Taxa_updated, Depth_Stratum, Site) %>% 
  mutate(av_weight = mean(StdWt)) %>% 
  ungroup() %>% 
  select(Depth_Stratum, Taxa_updated, av_weight) %>% 
  unique() %>% 
  group_by(Taxa_updated) %>% 
  mutate(total_weight = sum(av_weight)) %>% 
  mutate(percent_depth = av_weight/total_weight*100) %>% 
  select(Depth_Stratum, Taxa_updated, percent_depth)

write.csv(Percentage_depth, "Percentage_depth.csv")


# Find biomass per species, depth & site
abundance_deployment <- Mesomizer_species %>%
  select(Site, daylight, Depth_Stratum, Deployment, Taxa_updated, Abd_Std_nosm3_sp) %>%
  group_by(Site, daylight, Depth_Stratum, Deployment, Taxa_updated) %>%
  summarise(StdAbd = sum(Abd_Std_nosm3_sp)) %>% #one weight per species per deployment
  ungroup() %>%
  group_by(daylight, Taxa_updated, Depth_Stratum) %>%  
  summarise(abd_mean_depth = mean(StdAbd)) %>% #one weight per species per day/night & depth (average deployments)
   ungroup() %>% 
 mutate(g_m2 = case_when(
    Depth_Stratum == "E" ~ abd_mean_depth * 200,
    Depth_Stratum == "UM" ~ abd_mean_depth * 200,
    Depth_Stratum == "LM" ~ abd_mean_depth * 600
  )) %>% #convert from g m-3 to g m-2 by multipling by depth sampled. E = 200, UM = 200, LM = 600
  group_by(daylight, Taxa_updated) %>%
  summarise(
   abd_wc_nosm2_sp = sum(g_m2, na.rm = TRUE) #one weight per species per whole water column (add each layer)
  ) %>% 
  ungroup() %>% 
  group_by(Taxa_updated) %>% 
  summarise(
    abd_total_gm2_sp = mean(abd_wc_nosm2_sp) #average day and night values
  )

write.csv(abundance_deployment, "abundance_av_wc.csv")
```

#find biomass per species, depth & site - SIA chapter

```{r}

SIA_species <- catchcomp_total1 %>% 
  filter(Taxa_updated %in% c("Euphausia similis", "Thysannoessa macura", "Euphausia triacantha", "Gennadas spp.","Sergestes spp.", "Themisto spp", "Electrona antarctica", "Lampanyctus australis", "Nannobrachium achirus", "Cyclothone spp.", "Bathylagus spp.", "Cranchidae", "Chaetognath", "Gymnosomata", "Pyrosoma atlanticum","Salpa thompsoni", "Atolla wyvillei", "Periphylla periphylla")) 

Percentage_depth_SIA <- SIA_species %>% 
  select(Site, daylight, Depth_Stratum, Deployment, Taxa_updated, Weight_Std_gm3_sp) %>%
  group_by(Site, daylight, Depth_Stratum, Deployment, Taxa_updated) %>%
  summarise(StdWt = sum(Weight_Std_gm3_sp), .groups = "drop") %>% # Sum per species per deployment
  group_by(Taxa_updated, Depth_Stratum, Site) %>% 
  summarise(av_weight = mean(StdWt), .groups = "drop") %>% # Average across deployments
  group_by(Taxa_updated, Site) %>% 
  mutate(total_weight = sum(av_weight)) %>% # Total weight per taxa
  mutate(percent_depth = av_weight / total_weight * 100) %>% 
  ungroup() %>%
  select(Depth_Stratum, Taxa_updated, percent_depth, Site) %>% 
  ungroup() %>% 
  select(Depth_Stratum, Taxa_updated, percent_depth) %>%
  group_by(Taxa_updated) %>%
  mutate(migration = if_else(any(percent_depth >= 80 & percent_depth <= 100), "resident", "migrator")) %>%
  ungroup()


write.csv(Percentage_depth_SIA, "Resident_v_migrator.csv")



# Find biomass per species, depth & site
Biomass_deployment_SIA <- SIA_species %>%
  select(Site, daylight, Depth_Stratum, Deployment, Taxa_updated, Weight_Std_gm3_sp) %>%
  group_by(Site, daylight, Depth_Stratum, Deployment, Taxa_updated) %>%
  summarise(StdWt = sum(Weight_Std_gm3_sp)) %>% #one weight per species per deployment
  ungroup() %>%
  group_by(daylight, Taxa_updated, Depth_Stratum) %>%  
  summarise(weight_mean_depth = mean(StdWt)) %>% #one weight per species per day/night & depth (average deployments)
   ungroup() %>% 
 mutate(g_m2 = case_when(
    Depth_Stratum == "E" ~ weight_mean_depth * 200,
    Depth_Stratum == "UM" ~ weight_mean_depth * 200,
    Depth_Stratum == "LM" ~ weight_mean_depth * 600
  )) %>% #convert from g m-3 to g m-2 by multipling by depth sampled. E = 200, UM = 200, LM = 600
  group_by(daylight, Taxa_updated) %>%
  summarise(
    Weight_wc_gm2_sp = sum(g_m2, na.rm = TRUE) #one weight per species per whole water column (add each layer)
  ) %>% 
  ungroup() %>% 
  group_by(Taxa_updated) %>% 
  summarise(
    weight_total_gm2_sp = mean(Weight_wc_gm2_sp) #average day and night values
  )

```




