---
title: "Lengths_SOLACE"
output: html_document
date: "2024-05-29"
---

# Load data -------------------------------------------------------------

```{r}

library(ggplot2)
library(ggrepel)
library(tidyverse)
library(readr)
library(dplyr)
rm(list =ls()) # clear memory
Length_mm <- read.csv("C:/Users/kbaker5/OneDrive - University of Tasmania/Desktop/PhD_Salamanca/RstudioProjects/02_MesoMizer/input/Input_02_IN2020_V08_Lengths.csv")

```

#Find max length for missing species

```{r}
#SOLACE data
# Gennadas_L/W <- y = 0.0381x - 0.6585 (r2 = 0.9)
#Sergestes_L/W <- y = 0.029x - 0.5357 (r2 = 0.9)
# themisto_/W <- y = 0.0094x - 0.055 (r2 = 0.5)
#s. thompsoni_L/W <- y = 0.1417x-0.8843 (r2 = 0.5)
#p. atlanticum_L/W <- y = 0.7433x - 18.2 (r2 = 0.6668)

#Jellyfish - lit sources

#CW = 10^(2.767*log_10 (TL)-3.643) - Kwong et al 2020
#DW = CW/0.072 - Davis & Wiebe (1985)
#WW = DW/0.04 - Kiorboe 2013

#Chaetognath - lit sources

#CW = 0.0001352*TL^3.1545*0.367 - kwong et al 2020
#DW = CW/0.39 - Davis & Wiebe
#WW = DW/0.053 - Ikeda & Kirkwood (1989)

#Squid

#CW = 10^(2.611*log_10 (TL)-3.5)*55.44 - kwong et al 2020
#DW = CW/0.578 Ikeda & Bruce (1986)
#WW = DW/0.19 # Ahmad et al 2015




Gennadas_max_mm <- Length_mm %>% 
  filter(Taxa_updated %in% c("Gennadas spp.", "Gennadas gilchristi")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(max_g = 0.0381*Length_mm - 0.6585)

Sergestes_max_mm <- Length_mm %>% 
  filter(Taxa_updated %in% c("Sergestes spp.")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(max_g = 0.029*Length_mm - 0.5357)

Themisto_max_mm <-  Length_mm %>% 
  filter(Taxa_updated %in% c("Themisto gaudichaudii")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(max_g = 0.0094*Length_mm - 0.055)

S_thompsoni <-  Length_mm %>% 
  filter(Taxa_updated %in% c("Salpa thompsoni - solitary juv", "Salpa thompsoni - aggregate", "Salpa thompsoni - solitary")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(max_g = 0.1417*Length_mm - 0.6585)


Atolla <-  Length_mm %>% 
  filter(Taxa_updated %in% c("Atolla wyvillei")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(CW = 10^(2.767*log10(Length_mm)-3.643)) %>% 
  mutate(DW = CW/0.072) %>% 
  mutate(WW = DW/0.04) %>% 
  mutate(max_g = WW *0.001)


Peryphylla <-  Length_mm %>% 
  filter(Taxa_updated %in% c("Periphylla periphylla")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(CW = 10^(2.767*log10(Length_mm)-3.643)) %>% 
  mutate(DW = CW/0.072) %>% 
  mutate(WW = DW/0.04) %>% 
  mutate(max_g = WW *0.001)

Chaetognath <- Length_mm %>% 
  filter(Taxa_updated %in% c("Phylum Chaetognatha - undifferentiated")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(CW = 0.0001352*Length_mm^3.1545*0.367) %>% 
  mutate(DW = CW/0.39) %>% 
  mutate(WW = DW/0.053) %>% 
  mutate(max_g = WW *0.001)


Cranchiidae <- Length_mm %>% 
  filter(Taxa_updated %in% c("Cranchiidae - undifferentiated")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(CW = 10^(2.611*log10(Length_mm)-3.5)*55.44) %>% 
  mutate(DW = CW/0.578) %>% 
  mutate(WW = DW/0.19) %>% 
  mutate(max_g = WW *0.001)

Gymnosomata <- Length_mm %>% 
  filter(Taxa_updated %in% c("Order Gymnosomata - undifferentiated")) %>% 
  filter(Length_mm == max(Length_mm)) %>% 
  mutate(CW = 10^(2.611*log10(Length_mm)-3.5)*55.44) %>% 
  mutate(DW = CW/0.578) %>% 
  mutate(WW = DW/0.19) %>% 
  mutate(max_g = WW *0.001)


```

